-- Roles, warehouses, grants. See design doc §11.2.
-- Run as ACCOUNTADMIN.

USE DATABASE PEOPLE_ANALYTICS;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS WH_PA_DEV
    WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_PA_PROD
    WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- Functional roles (per design doc §11.2)
CREATE ROLE IF NOT EXISTS PA_PLATFORM_ADMIN
    COMMENT = 'Owns roles, schemas, masking policies, row-access policies.';
CREATE ROLE IF NOT EXISTS PA_ENGINEER
    COMMENT = 'Builds and tests dbt models. Read raw, write base/staging/core/marts.';
CREATE ROLE IF NOT EXISTS PA_ANALYST
    COMMENT = 'Read-only on marts and semantic. No PII.';
CREATE ROLE IF NOT EXISTS PA_SENSITIVE_HR
    COMMENT = 'Read sensitive HR (PII, employee_profile_scd full).';
CREATE ROLE IF NOT EXISTS PA_COMP
    COMMENT = 'Read compensation data. Subset of PA_SENSITIVE_HR.';
CREATE ROLE IF NOT EXISTS PA_SURVEY_RESTRICTED
    COMMENT = 'Read survey data only when k>=5 anonymity met.';
CREATE ROLE IF NOT EXISTS PA_AUDITOR
    COMMENT = 'Read everything for audits, write nothing.';

-- Hierarchy
GRANT ROLE PA_ENGINEER         TO ROLE PA_PLATFORM_ADMIN;
GRANT ROLE PA_SENSITIVE_HR     TO ROLE PA_PLATFORM_ADMIN;
GRANT ROLE PA_COMP             TO ROLE PA_SENSITIVE_HR;
GRANT ROLE PA_ANALYST          TO ROLE PA_ENGINEER;
GRANT ROLE PA_AUDITOR          TO ROLE PA_PLATFORM_ADMIN;

-- Warehouse access
GRANT USAGE ON WAREHOUSE WH_PA_DEV  TO ROLE PA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_PA_PROD TO ROLE PA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_PA_PROD TO ROLE PA_ANALYST;

-- Database / schema grants (engineer = build everywhere except restricted)
GRANT USAGE ON DATABASE PEOPLE_ANALYTICS TO ROLE PA_ENGINEER;
GRANT USAGE, CREATE SCHEMA ON DATABASE PEOPLE_ANALYTICS TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.RAW     TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.BASE    TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.STAGING TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.CORE    TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.MARTS   TO ROLE PA_ENGINEER;
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.SEMANTIC TO ROLE PA_ENGINEER;

-- Analyst: read-only on marts and semantic
GRANT USAGE ON DATABASE PEOPLE_ANALYTICS TO ROLE PA_ANALYST;
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.MARTS    TO ROLE PA_ANALYST;
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.SEMANTIC TO ROLE PA_ANALYST;
GRANT SELECT ON ALL TABLES    IN SCHEMA PEOPLE_ANALYTICS.MARTS TO ROLE PA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PEOPLE_ANALYTICS.MARTS TO ROLE PA_ANALYST;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PEOPLE_ANALYTICS.SEMANTIC TO ROLE PA_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PEOPLE_ANALYTICS.SEMANTIC TO ROLE PA_ANALYST;

-- Sensitive HR / Comp / Survey: granted to restricted schemas only
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.CORE_RESTRICTED  TO ROLE PA_SENSITIVE_HR;
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.MARTS_RESTRICTED TO ROLE PA_SENSITIVE_HR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PEOPLE_ANALYTICS.CORE_RESTRICTED  TO ROLE PA_SENSITIVE_HR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PEOPLE_ANALYTICS.MARTS_RESTRICTED TO ROLE PA_SENSITIVE_HR;

-- Audit schema: platform admin owns, auditor reads
GRANT ALL ON SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_PLATFORM_ADMIN;
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_AUDITOR;
GRANT SELECT ON ALL TABLES    IN SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_AUDITOR;

-- Engineer gets INSERT on AUDIT for erasure procedure execution
GRANT USAGE ON SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_ENGINEER;
GRANT INSERT ON ALL TABLES    IN SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_ENGINEER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA PEOPLE_ANALYTICS.AUDIT TO ROLE PA_ENGINEER;
